num1 = input("please enter an integer: ")
print(num1)
num2 = input("please enter an integer: ")
print(num2)
num3 = input("please enter an integer: ")
print(num3)
sum_num = sum(num1, num2, num3)
print(num1 + num2 + num3)
print(num1 - num2)
print(num3 * num1)
print ((num1 + num2 + num3) / num3)